### ISSUE TITLE
akka0100 not left adjusted

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-2018#164]
aramaic inscription, but not working the way Hebrew does.

**Comment by emylonas** [comment]
It may be a problem with Aramaic - I found more that don't line up correctly. 
https://library.brown.edu/cds/projects/iip/results/?q=%28language%3Aarc%29&resultsPage=2 
I'm sure there are more

**Comment by crotger** [comment]
I'm assuming you meant this one? https://library.brown.edu/cds/projects/iip/viewinscr/akko0100/ 
The issue is with the CSS -- the lang is marked on the p and not the div on that inscription, so it seems the text in the p is right-aligned, but the p itself is still left-aligned. I think I can fix this by adding another CSS rule, but is this something we also want to enforce in the encoding? I've found a few of these now.

**Comment by emylonas** [comment]
better to fix the div and not the p, let me take a look.

**Comment by emylonas** [comment]
better to fix the div and not the p, let me take a look.

**Comment by emylonas** [comment]
Hmm - there are a lot that have the language attribute on the `<p>` because that's where the Hebrew template puts it. I think having the language attribute on the `<div>` is only there on some of the older files. I can test by adding it to the `<div>` for akko0100 and seeing what happens when the file is displayed. 

We should decide on what should happen and then enforce it. One more non-existent schematron rule...

**Comment by emylonas** [comment]
fixed.
